### PR TITLE
Add MRIReco.jl

### PR DESCRIPTION
**Pull request by tknopp**
This is a PR to include MRIReco.jl into MRHub. Currently, we just have an ISMRM abstract as a reference. Hope this is ok. Will update once a proper paper is written.

### CODE REVIEW

**Comment by dgallichan** [comment]
Great - thanks for adding. Hopefully the ISMRM abstract will be on Semantic Scholar soon and you will be able to build up citations.

**Comment by tknopp** [comment]
Thanks Daniel, do you know what the policy of MRM is, whether they accept software papers? I am aware of JOSS but wonder if it would not be more suitable to publish in a journal with MR audience.

**Comment by dgallichan** [comment]
I'm afraid I'm not sure, but I'm guessing they don't...    

btw. I changed the 'category' from 'image reconstruction' to 'reconstruction' to be consistent with the other packages.

**Comment by tknopp** [comment]
yes that should be consistent, thanks for changing

**Pull request merged**
