### PR TITLE
Automatically update citation count when site is built/deployed

### PR DESCRIPTION
**Pull request by notZaki**
From what I understand, the current setup requires manually running a matlab script to update the citation count along with the most recent commit date. 

This PR offers an alternative---it uses a jekyll plugin/hook to automatically update the citations/dates when the site is being built. So each commit will trigger the update. 
The script also has an extra step to count the number of packages. They now show up in the "Categories" dropdown list.

[Here's a preview.](https://mrhub-pr.netlify.com/) (The buttons are not using the recent CSS update)
It looks like the matlab script was run recently, so now is also a good opportunity to compare the results.

However, there is one big caveat: This doesn't work with Github-pages. I think it's because github only allows specific plugins ([see note here for details](https://jekyllrb.com/docs/plugins/installation/)). 
There's two ways to overcome this (there could be more):

1. Use a different hosting service, such as [netlify](https://www.netlify.com/) 
    + Con: This means that the url would change, e.g. `mrhub.netlify.com`. 
    + The current `github.io` url would have to redirect to the netlify url (relatively simple to do)
        + ... or a custom domain name could be purchased, e.g. `mrhub.org`, so that the url does not depend on where the website is hosted
    + Pro: Netlify has some nice features such as generating build logs and automatically generating a preview website---so if someone opens a pull request, netlify will generate a website that can be used to check the changes. 
2. Use travis to build the website, and then push the built site to the `gh-pages` branch.
    + Con: This requires setting up travis with an authorization key
    + Pro: Website will still be generated through github-pages

Or just leave things as they are (if it ain't broke...).

### CODE REVIEW

**Comment by dgallichan** [comment]
Firstly, thanks very much for your efforts here. This is great stuff.
Unfortunately I would say that, for the time being, I'm not overly keen on moving to yet another host - especially as I think it's quite OK if there are gaps of several months where the update script doesn't get run, as it's only for citation count and 'last update' date. The MATLAB approach is certainly not very elegant, but for the time-being at least it lets me see what is going on when I apply an update...  
Is it relatively easy to set it up so your script is run manually in the same way I do for the MATLAB script at the moment? I don't think it needs to run automatically, and that would save the need to move servers.

**Comment by notZaki** [comment]
To run the script manually:

- `cd` to the mrhub folder
- run `jekyll build` (assuming ruby/jekyll is installed).

This should update the `package.json` and `info.json` files, which can then be comitted. A diff can be used to check the changes.

One potential problem with the manual workflow is that the ruby script will use unauthenticated requests to the github api which are restricted to 60 requests/hour, as [mentioned here](https://developer.github.com/v3/#rate-limiting)). So running the script locally will not be possible once there are more than 60 github packages---it should still work if netlify runs it, though I haven't confirmed this. 
I don't know whether the matlab script has a similar limitation.

**Comment by dgallichan** [comment]
This method is definitely more elegant, thanks. I changed the date-format of all dates to be with the 'dash' separator now - but Yarra still breaks it...  Previously Yarra was left blank because the designated repo was the 'username' only, so I added 'yarraclient' as a specific repo, but it now shows with the exact time-of-day as well as the date - are you able to easily fix that please? I'm afraid I'm not familiar at all with Ruby

**Comment by dgallichan** [comment]
Also, I wondered if it's possible (and hopefully relatively simple) to disable the autoexecution of the script and only run it when required? - If I use `jekyll serve` then it re-runs the script every time a file changes - and the script itself changes two files, so then it keeps running in a loop!

**Comment by notZaki** [comment]
I opened another pull request since this one was already merged so any new changes won't be reflected here. That should resolve the issue with the time/date and the looping with `jekyll serve`.

Also, this PR added a `Gemfile`. This is probably not necessary for Github-pages (but was needed for netlify), so it could be deleted if it causes any problems.

**Pull request merged**
